#!/usr/local/bin/php
<?php
/*==============================================================================
 *  Title      : Build (publish) css and javascript files into the public_html dir
 *               It is a wrap for `gulp`.
 *  Author     : Digger (c) SAD-Systems <http://sad-systems.ru>
 *  Created on : 21.10.2015
 *==============================================================================
 * Console script
 * to run from command line
 * -----------------------------------------------------------------------------
 */

$a = $argv[1];

$o = [
    '',
    'css',
    'js',
];

if (!$a) {
    $a = $o[0];
}

chdir(dirname(__DIR__));

if ($a==$o[0]) { 
//--- Build all ------------------------------------------------------
    echo "\n";
    echo "Build all:\n"
       . "----------------------------------\n";
    system("gulp");    
    
}

if ($a==$o[1]) { 
//--- Build css --------------------------------------------------
    echo "\n";
    echo "Build css only:\n"
       . "----------------------------------\n";
    system("gulp build-css");    
    
}

if ($a==$o[2]) { 
//--- Build javascripts --------------------------------------------
    echo "\n";
    echo "Build javascripts only:\n"
       . "----------------------------------\n";
    system("gulp build-js");    
    
}

echo "done\n";